name: "Latest PR"
description: "Find the most recent open PR for a given branch"

inputs:
  branch:
    description: "Branch name to search (defaults to current branch)"
    required: false

outputs:
  pr-url:
    description: "The URL of the latest open PR"
    value: ${{ steps.find.outputs.pr-url }}

runs:
  using: "composite"
  steps:
    - name: Find latest PR
      id: find
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        branch="${{ inputs.branch }}"
        if [ -z "$branch" ]; then
          branch="${GITHUB_REF_NAME}"
        fi

        echo "Searching for open PRs with head=$branch"
        pr_url=$(gh pr list \
          --head "$branch" \
          --base main \
          --state open \
          --json url \
          --jq '.[0].url // empty')

        if [ -n "$pr_url" ]; then
          echo "✅ Found PR: $pr_url"
        else
          echo "ℹ️  No open PR found for branch $branch"
        fi

        echo "pr-url=$pr_url" >> "$GITHUB_OUTPUT"
